services:
  # app:
  #   build: .
  #   # ports:
  #   #   - "8080:8080"
  #   volumes:
  #     - ./public:/public
  #     - ./db:/db

  # DEV ONLY
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data
    profiles: ["dev"]

  stripecli:
    image: stripe/stripe-cli:latest
    volumes:
      - ~/.stripe:/root/.stripe
    # This configuration allows the Stripe CLI to forward webhooks to the host machine
    # on both WSL and native Linux systems. For native Linux (e.g., Ubuntu), set the
    # DOCKER_HOST_IP environment variable in your .env file to your host's IP (usually 172.17.0.1).
    # If this doesn't work, you can find the correct IP by running `ip addr show docker0 | grep inet`
    # The extra_hosts setting ensures host.docker.internal resolves correctly on Linux.
    command: listen --forward-to ${DOCKER_HOST_IP:-host.docker.internal}:3000/api/webhooks/stripe
    network_mode: "host"
    profiles: ["dev"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  psql_volume:
