import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";

import Link from "next/link";
import { env } from "~/env";
import { MountainIcon } from "lucide-react";
import { getServerAuthSession } from "~/server/auth";
import {
  SidebarUserMenu,
  SidebarMobile,
  SidebarDesktop,
} from "~/components/layout/sidebar";
import { ThemeProvider } from "next-themes";
import { CookieBanner } from "~/components/cookie-banner/cookieBanner";
import { Toaster } from "~/components/ui/toaster";
import { Footer } from "~/components/layout/footer";

export const metadata: Metadata = {
  title: env.APP_NAME,
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerAuthSession();

  return (
    <html
      lang="en"
      className={`${GeistSans.variable}`}
      suppressHydrationWarning
    >
      <body>
        <TRPCReactProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <div className="flex min-h-screen w-full">
              {/* Sidebar */}
              <div className="hidden h-full lg:fixed lg:block lg:w-64 lg:shrink-0 lg:border-r">
                <div className="flex h-full flex-col justify-between px-4 py-6">
                  <div className="flex h-full flex-col">
                    <div className="space-y-6">
                      <Link
                        href={env.APP_URL}
                        className="flex items-center gap-2 font-bold"
                        prefetch={false}
                      >
                        <MountainIcon className="h-6 w-6" />
                        <span className="font-mono text-lg">
                          {env.APP_NAME}
                        </span>
                      </Link>
                      <SidebarDesktop />
                    </div>
                    <div className="mt-auto">
                      <SidebarUserMenu user={session?.user} />
                    </div>
                  </div>
                </div>
              </div>
              {/* Main content area */}
              <div className="flex flex-1 flex-col lg:ml-64">
                {/* Mobile header */}
                <header className="sticky top-0 z-10 border-b bg-background/80 px-4 py-3 backdrop-blur-sm lg:hidden">
                  <div className="flex items-center justify-between">
                    <Link
                      href={env.APP_URL}
                      className="flex items-center gap-2 font-bold"
                    >
                      <MountainIcon className="h-6 w-6" />
                      <span className="font-mono text-lg">{env.APP_NAME}</span>
                    </Link>
                    <SidebarMobile user={session?.user} />
                  </div>
                </header>
                {/* Main content and footer wrapper */}
                <div className="flex flex-grow flex-col">
                  <main className="flex-grow p-4 lg:p-8">{children}</main>
                  <Footer />
                </div>
              </div>
            </div>
            <CookieBanner />
            <Toaster />
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
